#!/bin/bash
#
#
# Example usage: 
#   gweather
#	  - Get the weather for current location (GEO IP)
#   gweather <LOCATION>
#	  - Get the weather for a specified location
#   gweather <LOCATION> <LANG>
#	  - Get the weather for a specified location and language type
#
#

# We require 'curl' so check for it
if ! command -v curl &>/dev/null; then
	printf "%s\n" "[ERROR] weather: This command requires 'curl', please install it."
	return 1
fi

# If no arg is given, default to ip location
curl -H "Accept-Language: ${2:-en}" -m 10 "http://wttr.in/${1:-}" 2>/dev/null || printf "%s\n" "[ERROR] weather: Could not connect to weather service."
